In [8]:
import os
from pprint import pprint

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [9]:
RANDOM_STATE = 110

#데이터 불러오기
train_data = pd.read_csv('C:/Users/정주연/LGAimers_5/train.csv') # 모델 학습 파일 
test_data = pd.read_csv('C:/Users/정주연/LGAimers_5/test.csv') # 모델 테스트 파일 
df_sub = pd.read_csv('C:/Users/정주연/LGAimers_5/submission.csv') # 제출 파일

In [10]:
train_data

,Wip Line_Dam,Process Desc._Dam,Equipment_Dam,Model.Suffix_Dam,Workorder_Dam,Insp. Seq No._Dam,Insp Judge Code_Dam,CURE END POSITION X Collect Result_Dam,CURE END POSITION X Unit Time_Dam,CURE END POSITION X Judge Value_Dam,...,Production Qty Collect Result_Fill2,Production Qty Unit Time_Fill2,Production Qty Judge Value_Fill2,Receip No Collect Result_Fill2,Receip No Unit Time_Fill2,Receip No Judge Value_Fill2,WorkMode Collect Result_Fill2,WorkMode Unit Time_Fill2,WorkMode Judge Value_Fill2,target
0,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XA938-1,1,OK,240.0,NaN,NaN,...,7,NaN,NaN,127,NaN,NaN,1,NaN,NaN,Normal
1,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,3KPM0016-2,1,OK,240.0,NaN,NaN,...,185,NaN,NaN,1,NaN,NaN,0,NaN,NaN,Normal
2,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,4E1X9167-1,1,OK,1000.0,NaN,NaN,...,10,NaN,NaN,73,NaN,NaN,1,NaN,NaN,Normal
3,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,3K1X0057-1,1,OK,1000.0,NaN,NaN,...,268,NaN,NaN,1,NaN,NaN,0,NaN,NaN,Normal
4,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3HPM0007-1,1,OK,240.0,NaN,NaN,...,121,NaN,NaN,1,NaN,NaN,0,NaN,NaN,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3J1XF434-2,1,OK,240.0,NaN,NaN,...,318,NaN,NaN,1,NaN,NaN,0,NaN,NaN,Normal
40502,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,4E1XC796-1,1,OK,1000.0,NaN,NaN,...,14,NaN,NaN,197,NaN,NaN,1,NaN,NaN,Normal
40503,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,4C1XD438-1,1,OK,240.0,NaN,NaN,...,1,NaN,NaN,27,NaN,NaN,1,NaN,NaN,Normal
40504,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,3I1XA258-1,1,OK,1000.0,NaN,NaN,...,117,NaN,NaN,1,NaN,NaN,0,NaN,NaN,Normal
40505,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3G1XA501-1,1,OK,240.0,NaN,NaN,...,320,NaN,NaN,1,NaN,NaN,0,NaN,NaN,AbNormal

In [11]:
df_sub

                                 Set ID    target
0      0001be084fbc4aaa9d921f39e595961b  AbNormal
1      0005bbd180064abd99e63f9ed3e1ac80    Normal
2      000948934c4140d883d670adcb609584  AbNormal
3      000a6bfd02874c6296dc7b2e9c5678a7    Normal
4      0018e78ce91343678716e2ea27a51c95    Normal
...                                 ...       ...
17356  ffea508b59934d689b540f95eb3fa730    Normal
17357  ffed8923c8a448a98afc641b770be153  AbNormal
17358  fff1e73734da40adbe805359b3efb462    Normal
17359  fff8e38bdd09470baf95f71e92075dec    Normal
17360  fffa83e0a13d4c2db4fd8bf905b517d4  AbNormal

[17361 rows x 2 columns]

In [13]:
train_data.isna()

,Wip Line_Dam,Process Desc._Dam,Equipment_Dam,Model.Suffix_Dam,Workorder_Dam,Insp. Seq No._Dam,Insp Judge Code_Dam,CURE END POSITION X Collect Result_Dam,CURE END POSITION X Unit Time_Dam,CURE END POSITION X Judge Value_Dam,...,Production Qty Collect Result_Fill2,Production Qty Unit Time_Fill2,Production Qty Judge Value_Fill2,Receip No Collect Result_Fill2,Receip No Unit Time_Fill2,Receip No Judge Value_Fill2,WorkMode Collect Result_Fill2,WorkMode Unit Time_Fill2,WorkMode Judge Value_Fill2,target
0,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
1,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
2,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
3,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
4,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
40502,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
40503,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
40504,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False
40505,False,False,False,False,False,False,False,False,True,True,...,False,True,True,False,True,True,False,True,True,False